## Import the relevant libraries

In [2]:
import numpy as np
import pandas as pd 

## Import the Preprocessed File

In [3]:
data_processed = pd.read_csv('Absenteeism_preprocessed.csv')
data_processed.head()

Unnamed: 0  Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0           0         0         0         0         1            7   
1           1         0         0         0         0            7   
2           2         0         0         0         1            7   
3           3         1         0         0         0            7   
4           4         0         0         0         1            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [4]:
# drop the 'Unnamed: 0 ' column
data_processed = data_processed.drop(['Unnamed: 0'], axis = 1)

## Create the Targets

In [5]:
#creating the targets into two classes. We find the median of absenteeism in hours and use that as our 'cutoff'
#between the two. Using the median function on the Abseenteeism column we can conclude that 
#Moderatley absent people are absent <= 3 hours and Excessively absent people are >= 4 hours
data_processed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_processed['Absenteeism Time in Hours'] > 3, 1, 0)

## Create a new column with the two targets

In [7]:
data_processed['Excessive Absenteeism'] = targets

In [8]:
data_processed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
# creating a new DF with added Targets column and operating off of a copy
data_with_targets = data_processed.copy()

In [10]:
# displaying the new df to check if it worked
data_with_targets.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [11]:
data_with_targets is data_processed

False

## Select the Inputs for the Logistic Regression

In [12]:
data_with_targets.shape

(700, 16)

In [13]:
# here we want to select all columns as our inputs and EXCLUDE the target column [Excessive Absenteeism]
# the : we pass as the first argument selects 'All' rows. Pass the '0' and '14' to select all rows except the last one
data_with_targets.iloc[:, 0: 14]

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,0:14]

## Standarize the Data

In [15]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [16]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [17]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [18]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [19]:
scaled_inputs.shape

(700, 14)

## Split the Data into Train, Test and then Shuffle

### Import the Relevant Module

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
          0.88046927,  0.26848661],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          1.78021889, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
          0.88046927, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [22]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, shuffle = True, random_state = 20)

In [23]:
print (x_train.shape, y_train.shape)

(560, 14) (560,)


In [24]:
print (x_test.shape, y_test.shape)

(140, 14) (140,)


## Logistic Regression with Sklearn

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the Model

In [26]:
reg = LogisticRegression()

In [27]:
reg.fit(x_train, y_train)

LogisticRegression()

In [28]:
reg.score(x_train, y_train)

0.7839285714285714

### Manually checking the accuracy of the Regression

In [29]:
model_outputs = reg.predict(x_train)
model_outputs

# these are the predictions of our model

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [30]:
#this is the target array
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [31]:
# we can't really tell whether or not the x_train array is much different than the y_train array so we 
# use a boolean statement to see if they are 'equal' to each other 
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [32]:
#calculate the total number of correct entries aka true entries
np.sum((model_outputs == y_train))

439

In [33]:
# Accuracy = total number of correct entries/number of observations
# First we find the total number of observations witht the following
model_outputs.shape[0]

560

In [34]:
# now we divide the total correct entries by the total number of observations
# and we get the accuracy of the trained model 
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.7839285714285714

### Find the Intercept

In [35]:
# find the intercept
reg.intercept_

array([-0.22206736])

In [36]:
# find the coefficients
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.18793677,
        -0.07062253,  0.70639316, -0.03986811, -0.20089491, -0.00456366,
         0.31933564, -0.135508  ,  0.38172443, -0.3332426 ]])

In [37]:
# we don't know which columns the 'reg.coeff' array is refering too. So we go to the 'unscaled_inputs'
# to find the names of the columns 
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [38]:
# we now store the column names in a variable called feature_name
feature_name = unscaled_inputs.columns.values

In [39]:
# now we will create a new dataframe that will contain the Column names with their intercepts and coefficients

#create the DF, create a column called 'Feature Name', and pull the data from the 'feature_name' variable
summary_table = pd.DataFrame(columns=['Feature Name'], data= feature_name)

#add the coefficient column to the DF
summary_table['Coefficient']= np.transpose(reg.coef_)

summary_table

Feature Name  Coefficient
0                  Reason 1     2.076018
1                  Reason 2     0.335048
2                  Reason 3     1.561623
3                  Reason 4     1.329274
4               Month Value     0.187937
5           Day of the Week    -0.070623
6    Transportation Expense     0.706393
7          Distance to Work    -0.039868
8                       Age    -0.200895
9   Daily Work Load Average    -0.004564
10          Body Mass Index     0.319336
11                Education    -0.135508
12                 Children     0.381724
13                     Pets    -0.333243

In [40]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()

summary_table

Feature Name  Coefficient
0                 Intercept    -0.222067
1                  Reason 1     2.076018
2                  Reason 2     0.335048
3                  Reason 3     1.561623
4                  Reason 4     1.329274
5               Month Value     0.187937
6           Day of the Week    -0.070623
7    Transportation Expense     0.706393
8          Distance to Work    -0.039868
9                       Age    -0.200895
10  Daily Work Load Average    -0.004564
11          Body Mass Index     0.319336
12                Education    -0.135508
13                 Children     0.381724
14                     Pets    -0.333243

In [41]:
# Here we are adding a new column thats shows the Odds Ratio. This is us interpreting the weights(coefficients)
# of the logistic regression

summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds Ratio
0                 Intercept    -0.222067    0.800861
1                  Reason 1     2.076018    7.972656
2                  Reason 2     0.335048    1.398007
3                  Reason 3     1.561623    4.766551
4                  Reason 4     1.329274    3.778301
5               Month Value     0.187937    1.206757
6           Day of the Week    -0.070623    0.931814
7    Transportation Expense     0.706393    2.026668
8          Distance to Work    -0.039868    0.960916
9                       Age    -0.200895    0.817998
10  Daily Work Load Average    -0.004564    0.995447
11          Body Mass Index     0.319336    1.376213
12                Education    -0.135508    0.873272
13                 Children     0.381724    1.464808
14                     Pets    -0.333243    0.716596

In [43]:
# Here we will sort the dataframe by the Odds Ratio column
summary_table.sort_values('Odds Ratio', ascending=False)

Feature Name  Coefficient  Odds Ratio
1                  Reason 1     2.076018    7.972656
3                  Reason 3     1.561623    4.766551
4                  Reason 4     1.329274    3.778301
7    Transportation Expense     0.706393    2.026668
13                 Children     0.381724    1.464808
2                  Reason 2     0.335048    1.398007
11          Body Mass Index     0.319336    1.376213
5               Month Value     0.187937    1.206757
10  Daily Work Load Average    -0.004564    0.995447
8          Distance to Work    -0.039868    0.960916
6           Day of the Week    -0.070623    0.931814
12                Education    -0.135508    0.873272
9                       Age    -0.200895    0.817998
0                 Intercept    -0.222067    0.800861
14                     Pets    -0.333243    0.716596